version: '3.8'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"

  api:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  prefect:
    build: .
    command: prefect server start
    ports:
      - "4200:4200"
    depends_on:
      - api

#  cli:
#    image: myappimage
#    environment:
#      - USERNAME=${USERNAME}
#      - PASSWORD=${PASSWORD}


#  prefect:
#    image: prefecthq/server:latest
#    environment:
#      PREFECT__BACKEND: server
#      PREFECT__SERVER__DATABASE_CONNECTION_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

#  prefect-ui:
#    image: prefecthq/ui:latest
#    ports:
#      - "8081:8080"
#    environment:
#      PREFECT_API_URL: http://prefect:4200
#    depends_on:
#      - prefect

volumes:
  postgres_data:
