"""Adjust scopezdz

Revision ID: 5e3a8ffd1b2b
Revises: ba205b4bf654
Create Date: 2024-03-10 22:36:09.650205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3a8ffd1b2b'
down_revision: Union[str, None] = 'ba205b4bf654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
