"""Adjust permissions

Revision ID: 99289767c14f
Revises: 8e2cda55d6fe
Create Date: 2024-03-10 13:50:37.154219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99289767c14f'
down_revision: Union[str, None] = '8e2cda55d6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'permissions', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'role_id')
    # ### end Alembic commands ###
